### ISSUE TITLE
The images are not found

### ISSUE THREAD

**Issue by Mobeidat** [tomi/presentation-artificial-intelligence#1]

**Comment by Mobeidat** [comment]
@tomi  any update?

**Comment by tomi** [comment]
Hi, I don't have the copyrights for the images used in this presentations, so I can't put them up for public distribution.

**Comment by Mobeidat** [comment]
Okay, can you please help me and send them to me privately(moathalobeidat@gmail.com). I want to see the full presentation.

**Comment by Mobeidat** [comment]
@tomi if you could share with me the full presentation privately I would highly appreciate it. Thanks in advance

**Comment by Mobeidat** [comment]
Any update?
